services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: test1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: