spring:
  application:
    name: payment-server
  profiles:
    active: local
  jpa:
    open-in-view: false

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
